title: Food For Thought
description: This website is for the posting of my weekly blogs
header_text: Food For Thought
footer_text: Copyright 2020 Verity Hutton
header_feature_image: ../uploads/last-supper-1024x512.jpg
bannerheight: 20vmax
logo: ../uploads/knife.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
